- name: bug
  color: d73a4a
  description: Something isn't working
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: documentation
  color: 0075ca
  description: Documentation-only changes
- name: security
  color: b60205
  description: Security-related issues
- name: discussion
  color: d4c5f9
  description: Design or product discussion
